### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by ashar02**

### CODE REVIEW

**Comment by zevarito** [comment]
@ashar02 were this PR closed accidentally? Let me know if I have to re-open, review and merge.

Thanks.

**Comment by zevarito** [comment]
@ashar02 Please in the future PR per commit, feature. Merged, Thanks!

**Comment by ashar02** [comment]
Okay!!

**Comment by zevarito** [comment]
@ashar02 did you notice a performance downgrade using latest revisions of
Licode as well?

On Monday, 9 May 2016, ashar_clary <notifications@github.com> wrote:

> Okay!!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/Licode-ErizoClientIOS/pull/26#issuecomment-217963385>
>


-- 
Sent from Gmail Mobile

**Comment by ashar02** [comment]
I am testing Licode from two platforms. One from Android and another from iOS. I used chrome on Android devices. And its performance is good. On iOS I am using this respository. If I use libjingle v 9814.2.0 then performance is quite better but if I use libjingle v 10604.2.2 (although it solves DTLS problem for arm64) but it shows poor performance (like stuck, disconnect or frame drop). I am in search of another version of libjingle which solves the DTLS problem as well as shows same performance as v 9814.2.0.

**Comment by zevarito** [comment]
Same issue here, please update if you found something, although looks like
a Licode issue to me, not libjingle.

On Monday, 9 May 2016, ashar_clary <notifications@github.com> wrote:

> I am testing Licode from two platforms. One from Android and another from
> iOS. I used chrome on Android devices. And its performance is good. On iOS
> I am using this respository. If I use libjingle v 9814.2.0 then performance
> is quite better but if I use libjingle v 10604.2.2 (although it solves DTLS
> problem for arm64) but it shows poor performance (like stuck, disconnect or
> frame drop). I am in search of another version of libjingle which solves
> the DTLS problem as well as shows same performance as v 9814.2.0.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/Licode-ErizoClientIOS/pull/26#issuecomment-217970712>
>


-- 
Sent from Gmail Mobile

**Comment by ashar02** [comment]
Okay!! let you know. Is there any Licode signaling message document available any where?

**Comment by zevarito** [comment]
No I don't think that protocol is documented.

On Monday, 9 May 2016, ashar_clary <notifications@github.com> wrote:

> Okay!! let you know. Is there any Licode signaling message document
> available any where?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/Licode-ErizoClientIOS/pull/26#issuecomment-217973680>
>


-- 
Sent from Gmail Mobile

**Comment by ashar02** [comment]
ok

**Comment by zevarito** [comment]
@ashar02 please check this commit @86180ed. Licode has changed they way how they send iceServers configuration so it were running without turn server. It was giving `nil` for all values, since Licode backend has a default stun server the connection was established in some escenarios.

**Pull request merged**
