### PR TITLE
Several fixes, attributes and data stream channel support

### PR DESCRIPTION
**Pull request by ashar02**
Few days back I merged your repo with mine. In my branch I fixed several issues and warnings.
Plus I tried to implement attributes and data stream support in this project. Please have a review and take picks you want.

### CODE REVIEW

**Comment by zevarito** [comment]
Hi @ashar02, is not clear to me why you have changed `NSString streamId` in favor to use a `NSDictionary`, IMO is harder to handle a dictionary since you never know what is/could be inside, in opposition the method firm is much more clear passing `streamId` which also is what Licode supports.

I am seeing a few conflicts that prevent a smooth merge, did you look at those?

Thanks.

**Comment by ashar02** [comment]
Hi @zevarito 
Yes you are right that streamId is quite easy to handle. But many time easy handling takes your control off. Anyway, the reason is that I want to display 'displayName' with each publish / subscribe streams. Also if some one publishes 'audio only' then I have to check from attributes and display video box to 'audio only stream'.

Let me know if you want to make these things in some other way?
Also I am checking the conflicted files to make it smooth!!

**Comment by zevarito** [comment]
@ashar02 well, I don't know about your particular use case, I moved lot of things into my app domain to avoid adding my personal use cases as-well trying to keep it simple and generic usable for everyone, also trying to keep it as closet to the Javascript API is good but that is not mandatory.

I have to review your changes with more time and in deep. I was planning to add some new features to the library that I want to discuss with you since we both seems to be the only ones involved on developing this. Perhaps we can start with that practice, discuss the implications before start coding so we can ensure an API that unless it is unavoidable doesn't brake previous versions. What do you say?

**Comment by ashar02** [comment]
@zevarito to show display name is very common need in every audio/video conferencing application. That is why I did this!!

I agree to discuss and adopt proactive approach before start coding.

**Comment by zevarito** [comment]
Hi @ashar02, so I was looking a little bit more around the `streamId` vs `NSDictionary`, I might be getting this wrong, but I am not identifying any practical use for the Dictionary inside the client code and signaling code, I am seeing that all methods have changed to support `dictionary` but it is only a "pass around" of it. If I am right on this, the core components should not be aware about all the metadata that you might want to associate with the stream, this can be easily supported by the "wrapper" app having a mapping there for stream ids and as many metadata you might want to handle there.

So, I am up for the data channel, code and example improvements and project meta/settings, but need to be convinced about the dictionary/streamId thing.

Let's try to PR as atomically as we can so it is easier to discuss review and merge, if we start them from master and keep the cycle everything will be smoother.

Let me know your thoughts.

**Comment by ashar02** [comment]
Okay, let me resend pull request after latest code merging.

**Pull request closed without merging**
