### PR TITLE
Build settings fixed.

### PR DESCRIPTION
**Pull request by ashar02**
Build settings fixed. I checked out the code to check the project settings. So I fixed this. You can take pull now.

### CODE REVIEW

**Comment by zevarito** [comment]
@ashar02 Could you make sure it merges correctly with `master` branch? Thanks!

**Comment by ashar02** [comment]
Are you facing any conflict in its merging?

**Comment by zevarito** [comment]
Yup, a lot. Please hold on cause I think I have a solution for the quality
stuff we discussed yesterday.

2016-05-10 11:50 GMT-03:00 ashar_clary <notifications@github.com>:

> Are you facing any conflict in its merging?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/Licode-ErizoClientIOS/pull/27#issuecomment-218181920>
>



-- 
Alvaro

**Comment by ashar02** [comment]
okay, let me send you again.

**Pull request closed without merging**
